language: csharp
mono: none
os: linux
dotnet: 5.0
script:
    - dotnet build ./DotNetNotebook.EnvMagicCommand -c Release
    - dotnet pack ./DotNetNotebook.EnvMagicCommand -c Release
deploy:
    - provider: script
      skip_cleanup: true
      script: dotnet nuget push DotNetNotebook.EnvMagicCommand/DotNetNotebook.EnvMagicCommand/bin/Release/DotNetNotebook.EnvMagicCommand.*.nupkg --api-key $NUGET_API_KEY --source nuget.org
      on:
          tags: true
          branch: main
